server:
  port: 8012 # Port aplikasi

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ckgldb # URL database PostgreSQL
    username: root # Username database
    password: root # Password database
    driver-class-name: org.postgresql.Driver # Driver database PostgreSQL\

  jpa:
    hibernate:
      ddl-auto: update # Mengupdate skema database secara otomatis
    show-sql: true # Menampilkan query SQL di konsol
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Dialek Hibernate untuk PostgreSQL
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080 # URI penerbit JWT (ganti sesuai kebutuhan)
  application:
    name: jwtspringboot
#  freemarker:
#    template-loader-path: classpath:/templates/
#    charset: UTF-8
#    cache: false
#    suffix: .html # Suffix untuk template Freemarker
#    check-template-location: true
#    content-type: text/html
#    expose-request-attributes: true
#    expose-session-attributes: true
#    expose-spring-macro-helpers: true
#    request-context-attribute: request
#    #spring.freemarker.default-encoding=UTF-8
#    settings:
#      template_update_delay: 0
#      number_format: 0.##########
#      datetime_format: yyyy-MM-dd HH:mm:ss
#      classic_compatible: true
#      template_exception_handler: ignore

jwt:
  secret: Kmi7oHVHyZ35KYEDatmO0jZ5SRuuhJLAcwsQycsgF8g= # Kunci rahasia JWT (ganti dengan kunci yang lebih aman)
  expiration: 3600000 # Waktu kedaluwarsa token JWT (dalam milidetik)

logging:
  level:
    root: INFO # Level logging root
    com.demo: DEBUG # Level logging untuk package com.example

management:
  endpoints:
    web:
      exposure:
        include: info