server:
  port: 8012 # Port aplikasi

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ckgldb # URL database PostgreSQL
    username: root # Username database
    password: root # Password database
    driver-class-name: org.postgresql.Driver # Driver database PostgreSQL\

  jpa:
    hibernate:
      ddl-auto: update # Mengupdate skema database secara otomatis
    show-sql: true # Menampilkan query SQL di konsol
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect # Dialek Hibernate untuk PostgreSQL
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080 # URI penerbit JWT (ganti sesuai kebutuhan)
  application:
    name: jwtspringboot
  redis:
    host: 10.9.37.229
    port: 6379
    password:  # Set if your Redis requires authentication
    database: 14  # Default DB index
    ssl: false

mybatis-plus:
  mapper-locations: classpath:/mappers/**/*.xml
  type-aliases-package: com.demo.jwtspringboot.model.dao
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: input
      logic-delete-value: 1
      logic-not-delete-value: 0
jwt:
  secret: Kmi7oHVHyZ35KYEDatmO0jZ5SRuuhJLAcwsQycsgF8g= # Kunci rahasia JWT (ganti dengan kunci yang lebih aman)
  expiration: 3600000 # Waktu kedaluwarsa token JWT (dalam milidetik)

logging:
  level:
    root: DEBUG # Level logging root
    com:
      demo: DEBUG # Level logging untuk package com.example
    org:
      springframework: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: info